[package]
name = "torrent-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
serde = {version = "1.0.228", features = ["derive"] }
serde_bencode = "0.2.4"
serde_bytes = "0.11.19"
